export { User, type IUser } from "./User";
export { Student, type IStudent } from "./Student";
export { Teacher, type ITeacher } from "./Teacher";
export { Course, type ICourse } from "./Course";
export { Enrollment, type IEnrollment } from "./Enrollment";
export { Timetable, type ITimetable } from "./Timetable";
export { Announcement, type IAnnouncement } from "./Announcement";
export { Attendance, type IAttendance } from "./Attendance";
export { Result, type IResult } from "./Result";